#!/bin/bash

RETURN=0
CLANGF=$(which clang-format)
if [ $? -ne 0 ]; then
    echo "[!] clang-format not installed. Unable to check source file format policy." >&2
    exit 1
fi

FILES=`git diff --cached --name-only --diff-filter=ACMR | grep -E "\.(c|cpp|h|hpp)$"`
for FILE in $FILES; do
    $CLANGF -style=file --dry-run --Werror $FILE &> /dev/null
    if [ $? -ne 0 ]; then
        echo "[!] $FILE does not respect the agreed coding style." >&2
        RETURN=1
    fi
done

if [ $RETURN -eq 0 ]; then
	#echo "" >&2
	echo "Code style check passed" >&2
fi

exit $RETURN
